language: generic
env:
  - BUILD='--from alpine'
  - BUILD='--from ubuntu --apt cowsay'
  - BUILD='--from centos'
  - BUILD='--from fedora --run "touch a"'
  - BUILD='--from debian'
  - BUILD='--from opensuse'

install:

  # install plash and dependencies
  - sudo apt-get install python3 python3-pip unionfs-fuse uidmap
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashcache

script:

  # load the plash cache
  - plash sudo tar -xf ~/plashcache/data.tar -C / || plash init

  - plash run $BUILD --  sh -c 'cat /etc/*-release'

  # save the plash cache
  - plash sudo tar -cf ~/plashcache/data.tar ~/.plashdata
