language: generic
env:
  - BUILD='-i alpine'
  - BUILD='-i ubuntu --apt cowsay'
  - BUILD='-i centos'
  - BUILD='-i fedora --run "touch a"'
  - BUILD='-i debian'
  - BUILD='-i opensuse'

install:

  # install plash and dependencies
  - sudo apt-get install python3 python3-pip unionfs-fuse uidmap
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashcache

script:

  # load the plash cache
  - plash sudo tar -xf ~/plashcache/data.tar -C / || plash init

  - plash run --include-string " $BUILD" -- cat /etc/*-release

  # save the plash cache
  - plash sudo tar -cf ~/plashcache/data.tar ~/.plashdata
