language: generic
env:
  - BUILD='--alpine'
  - BUILD='-f --ubuntu cowsay'

install:

  # install plash and dependencies
  - sudo apt-get install python3 python3-pip unionfs-fuse uidmap
  - sudo pip3 install plash

cache:
  directories:
    - ~/data.tar

script:

  # load the plash cache
  - plash sudo tar -xvf ~/data.tar -C /
  - plash init

  - plash run --include-string " $BUILD" -- printf 'heellow'

  - ls ~/plashcache/data.tar

  # save the plash cache
  - plash sudo tar -cvf --sort=name ~/data.tar ~/.plashdata
