language: generic
env:
  - BUILD='--alpine'
  - BUILD='-f --ubuntu'

install:
  - sudo apt-get install python3 python3-pip unionfs-fuse uidmap
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashdata/mydata.tar

script:
  - plash init
  - plash run --incude-string " $BUILD" -- printf 'heellow'
